set encoding=UTF-8

syntax on                    " Enable syntax highlight
set number                   " Show line numbers
set expandtab                " Tabs always insert spaces
set autoindent               " Automatic indentation
set shiftwidth=2             " Sets indentation as 2 spaces
set tabstop=2                " Makes a tab count for every 2 spaces
set backspace=2              " Use standard backspace behavior
set scrolloff=5              " Always shows at least 5 lines above and below the cursor
set sw=2                     " Sets shift width
set sts=2                    " Makes spaces 'feel like' tabs
set hlsearch                 " Highlights search results
set encoding=utf-8           " Force UTF-8 encoding
set fileformat=unix          " Force file format to UNIX
set hidden                   " Allow vim to switch do another buffer w/o saving
