export ZSH="$HOME"/.oh-my-zsh

ZSH_THEME="gnzh"

plugins=(
	git 
	tmux 
	ruby
	zsh-syntax-highlighting
	zsh-autosuggestions
)

HIST_STAMPS="mm/dd/yyyy"

export EDITOR='vim'

export LANG=en_US.UTF-8

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases

source $HOME/.zshenv
eval "$(rbenv init -)"

source $ZSH/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
