# Path to your oh-my-zsh installation.
export ZSH="/Users/raphaeltelatim/.oh-my-zsh"

ZSH_THEME="gnzh"

plugins=(git tmux)

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases

# Alias
alias fiat='cd ~/autocelio/fiat'
alias produquimica='cd ~/autocelio/produquimica'
alias vbr='cd ~/autocelio/vbr'
alias vanilla='cd ~/autocelio/vanilla/padrao'
alias fiat='cd ~/autocelio/fiat'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
   export EDITOR='mvim'
fi

export LANG=en_US.UTF-8

source $HOME/.zshenv
eval "$(rbenv init -)"

source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
